MIN_AREA = 100
MIN_WIDTH, MIN_HEIGHT = 2, 8
MIN_RATIO, MAX_RATIO = 0.25, 1.0

MAX_DIAG_MULTIPLYER = 5 
MAX_ANGLE_DIFF = 12.0 
MAX_AREA_DIFF = 0.5
MAX_WIDTH_DIFF = 0.8 
MAX_HEIGHT_DIFF = 0.2
MIN_N_MATCHED = 3

PLATE_WIDTH_PADDING = 1.3
PLATE_HEIGHT_PADDING = 1.5
MIN_PLATE_RATIO = 3
MAX_PLATE_RATIO = 10

# UPLOAD_FOLDER = 'D:/Programing/projects/PINOKIO_TEXT_DETECTOR/ocr_api/static/img/'
UPLOAD_FOLDER = '/home/ubuntu/PINOKIO_LIMYEONSANG/ocr_api/static/img'
ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg'])